# fly.toml app configuration file generated for pets-next-door on 2023-09-05T01:47:15+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pets-next-door"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
