// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "petsnextdoordev@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/callback/kakao": {
            "get": {
                "description": "Kakao 로그인 콜백을 처리하고, 사용자 기본 정보와 함께 Firebase Custom Token을 발급합니다.",
                "tags": [
                    "auth"
                ],
                "summary": "Kakao 회원가입 콜백 API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.KakaoCallbackResponse"
                        }
                    }
                }
            }
        },
        "/auth/login/kakao": {
            "get": {
                "tags": [
                    "auth"
                ],
                "summary": "Kakao 로그인 페이지로 redirect 합니다.",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/breeds": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "견/묘종을 조회합니다.",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "페이지 번호",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "페이지 사이즈",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "dog",
                            "cat"
                        ],
                        "type": "string",
                        "description": "펫 종류",
                        "name": "pet_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/commonviews.PaginatedView-pet_BreedView"
                        }
                    }
                }
            }
        },
        "/media/images": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "이미지를 업로드합니다.",
                "parameters": [
                    {
                        "type": "file",
                        "description": "이미지 파일",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/media.MediaView"
                        }
                    }
                }
            }
        },
        "/media/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "미디어를 ID로 조회합니다.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "미디어 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/media.MediaView"
                        }
                    }
                }
            }
        },
        "/posts/sos": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "돌봄급구 게시글을 조회합니다.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "작성자 ID",
                        "name": "author_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "페이지 번호",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "페이지 사이즈",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "newest",
                            "deadline"
                        ],
                        "type": "string",
                        "description": "정렬 기준",
                        "name": "sort_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/commonviews.PaginatedView-sos_post_FindSosPostResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "FirebaseAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "돌봄급구 게시글을 수정합니다.",
                "parameters": [
                    {
                        "description": "돌봄급구 수정 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sos_post.UpdateSosPostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "FirebaseAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "돌봄급구 게시글을 업로드합니다.",
                "parameters": [
                    {
                        "description": "돌봄급구 게시글 업로드 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sos_post.WriteSosPostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/sos_post.WriteSosPostResponse"
                        }
                    }
                }
            }
        },
        "/posts/sos/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "게시글 ID로 돌봄급구 게시글을 조회합니다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "게시글 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sos_post.FindSosPostResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "파이어베이스 가입 이후 정보를 입력 받아 유저를 생성합니다.",
                "parameters": [
                    {
                        "description": "사용자 회원가입 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/user.RegisterUserResponse"
                        }
                    }
                }
            }
        },
        "/users/check/nickname": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "닉네임 중복 여부를 조회합니다.",
                "parameters": [
                    {
                        "description": "사용자 닉네임 중복 조회 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CheckNicknameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.CheckNicknameView"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "FirebaseAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "내 프로필 정보를 조회합니다.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.MyProfileResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "FirebaseAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "내 프로필 정보를 수정합니다.",
                "parameters": [
                    {
                        "description": "사용자 프로필 수정 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UpdateUserResponse"
                        }
                    }
                }
            }
        },
        "/users/me/pets": {
            "get": {
                "security": [
                    {
                        "FirebaseAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users",
                    "pets"
                ],
                "summary": "내 반려동물 목록을 조회합니다.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pet.FindMyPetsView"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "FirebaseAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users",
                    "pets"
                ],
                "summary": "내 반려동물을 등록합니다.",
                "parameters": [
                    {
                        "description": "반려동물 등록 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pet.AddPetsToOwnerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users/status": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "이메일로 유저의 가입 상태를 조회합니다.",
                "parameters": [
                    {
                        "description": "사용자 가입 상태 조회 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserStatusView"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.KakaoCallbackResponse": {
            "type": "object",
            "properties": {
                "authToken": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fbProviderType": {
                    "$ref": "#/definitions/user.FirebaseProviderType"
                },
                "fbUid": {
                    "type": "string"
                },
                "photoURL": {
                    "type": "string"
                }
            }
        },
        "commonviews.PaginatedView-pet_BreedView": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pet.BreedView"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "commonviews.PaginatedView-sos_post_FindSosPostResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sos_post.FindSosPostResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "media.MediaType": {
            "type": "string",
            "enum": [
                "image"
            ],
            "x-enum-varnames": [
                "IMAGE_MEDIA_TYPE"
            ]
        },
        "media.MediaView": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mediaType": {
                    "$ref": "#/definitions/media.MediaType"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "pet.AddPetRequest": {
            "type": "object",
            "required": [
                "birth_date",
                "breed",
                "name",
                "neutered",
                "pet_type",
                "sex",
                "weight_in_kg"
            ],
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "neutered": {
                    "type": "boolean"
                },
                "pet_type": {
                    "enum": [
                        "dog",
                        "cat"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/pet.PetType"
                        }
                    ]
                },
                "sex": {
                    "enum": [
                        "male",
                        "female"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/pet.PetSex"
                        }
                    ]
                },
                "weight_in_kg": {
                    "type": "number"
                }
            }
        },
        "pet.AddPetsToOwnerRequest": {
            "type": "object",
            "required": [
                "pets"
            ],
            "properties": {
                "pets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pet.AddPetRequest"
                    }
                }
            }
        },
        "pet.BreedView": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pet_type": {
                    "$ref": "#/definitions/pet.PetType"
                }
            }
        },
        "pet.FindMyPetsView": {
            "type": "object",
            "properties": {
                "pets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pet.PetView"
                    }
                }
            }
        },
        "pet.PetSex": {
            "type": "string",
            "enum": [
                "male",
                "female"
            ],
            "x-enum-varnames": [
                "PetSexMale",
                "PetSexFemale"
            ]
        },
        "pet.PetType": {
            "type": "string",
            "enum": [
                "dog",
                "cat"
            ],
            "x-enum-varnames": [
                "PetTypeDog",
                "PetTypeCat"
            ]
        },
        "pet.PetView": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "neutered": {
                    "type": "boolean"
                },
                "pet_type": {
                    "$ref": "#/definitions/pet.PetType"
                },
                "sex": {
                    "$ref": "#/definitions/pet.PetSex"
                },
                "weight_in_kg": {
                    "type": "number"
                }
            }
        },
        "sos_post.CareType": {
            "type": "string",
            "enum": [
                "foster",
                "visiting"
            ],
            "x-enum-varnames": [
                "CareTypeFoster",
                "CareTypeVisiting"
            ]
        },
        "sos_post.CarerGender": {
            "type": "string",
            "enum": [
                "male",
                "female"
            ],
            "x-enum-varnames": [
                "CarerGenderMale",
                "CarerGenderFemale"
            ]
        },
        "sos_post.ConditionView": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "sos_post.FindSosPostResponse": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "integer"
                },
                "care_type": {
                    "$ref": "#/definitions/sos_post.CareType"
                },
                "carer_gender": {
                    "$ref": "#/definitions/sos_post.CarerGender"
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sos_post.ConditionView"
                    }
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date_end_at": {
                    "type": "string"
                },
                "date_start_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/media.MediaView"
                    }
                },
                "pets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pet.PetView"
                    }
                },
                "reward": {
                    "type": "string"
                },
                "reward_amount": {
                    "$ref": "#/definitions/sos_post.RewardAmount"
                },
                "thumbnail_id": {
                    "type": "integer"
                },
                "time_end_at": {
                    "type": "string"
                },
                "time_start_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "sos_post.RewardAmount": {
            "type": "string",
            "enum": [
                "hour"
            ],
            "x-enum-varnames": [
                "RewardAmountHour"
            ]
        },
        "sos_post.UpdateSosPostRequest": {
            "type": "object",
            "required": [
                "care_type",
                "carer_gender",
                "content",
                "date_end_at",
                "date_start_at",
                "id",
                "image_ids",
                "reward",
                "reward_amount",
                "time_end_at",
                "time_start_at",
                "title"
            ],
            "properties": {
                "care_type": {
                    "enum": [
                        "foster",
                        "visiting"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sos_post.CareType"
                        }
                    ]
                },
                "carer_gender": {
                    "enum": [
                        "male",
                        "female"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sos_post.CarerGender"
                        }
                    ]
                },
                "condition_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "content": {
                    "type": "string"
                },
                "date_end_at": {
                    "type": "string"
                },
                "date_start_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "pet_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "reward": {
                    "type": "string"
                },
                "reward_amount": {
                    "enum": [
                        "hour"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sos_post.RewardAmount"
                        }
                    ]
                },
                "time_end_at": {
                    "type": "string"
                },
                "time_start_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "sos_post.WriteSosPostRequest": {
            "type": "object",
            "required": [
                "care_type",
                "carer_gender",
                "content",
                "date_end_at",
                "date_start_at",
                "image_ids",
                "reward",
                "reward_amount",
                "time_end_at",
                "time_start_at",
                "title"
            ],
            "properties": {
                "care_type": {
                    "enum": [
                        "foster",
                        "visiting"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sos_post.CareType"
                        }
                    ]
                },
                "carer_gender": {
                    "enum": [
                        "male",
                        "female"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sos_post.CarerGender"
                        }
                    ]
                },
                "condition_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "content": {
                    "type": "string"
                },
                "date_end_at": {
                    "type": "string"
                },
                "date_start_at": {
                    "type": "string"
                },
                "image_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "pet_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "reward": {
                    "type": "string"
                },
                "reward_amount": {
                    "enum": [
                        "hour"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/sos_post.RewardAmount"
                        }
                    ]
                },
                "time_end_at": {
                    "type": "string"
                },
                "time_start_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "sos_post.WriteSosPostResponse": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "integer"
                },
                "care_type": {
                    "$ref": "#/definitions/sos_post.CareType"
                },
                "carer_gender": {
                    "$ref": "#/definitions/sos_post.CarerGender"
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sos_post.ConditionView"
                    }
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date_end_at": {
                    "type": "string"
                },
                "date_start_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/media.MediaView"
                    }
                },
                "pets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pet.PetView"
                    }
                },
                "reward": {
                    "type": "string"
                },
                "reward_amount": {
                    "$ref": "#/definitions/sos_post.RewardAmount"
                },
                "thumbnail_id": {
                    "type": "integer"
                },
                "time_end_at": {
                    "type": "string"
                },
                "time_start_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "user.CheckNicknameRequest": {
            "type": "object",
            "required": [
                "nickname"
            ],
            "properties": {
                "nickname": {
                    "type": "string"
                }
            }
        },
        "user.CheckNicknameView": {
            "type": "object",
            "properties": {
                "isAvailable": {
                    "type": "boolean"
                }
            }
        },
        "user.FirebaseProviderType": {
            "type": "string",
            "enum": [
                "email",
                "google",
                "apple",
                "kakao"
            ],
            "x-enum-varnames": [
                "FirebaseProviderTypeEmail",
                "FirebaseProviderTypeGoogle",
                "FirebaseProviderTypeApple",
                "FirebaseProviderTypeKakao"
            ]
        },
        "user.MyProfileResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fbProviderType": {
                    "$ref": "#/definitions/user.FirebaseProviderType"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "profileImageUrl": {
                    "type": "string"
                }
            }
        },
        "user.RegisterUserRequest": {
            "type": "object",
            "required": [
                "email",
                "fbProviderType",
                "fbUid",
                "fullname",
                "nickname",
                "profileImageId"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "fbProviderType": {
                    "$ref": "#/definitions/user.FirebaseProviderType"
                },
                "fbUid": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "profileImageId": {
                    "type": "integer"
                }
            }
        },
        "user.RegisterUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fbProviderType": {
                    "$ref": "#/definitions/user.FirebaseProviderType"
                },
                "fbUid": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "profileImageUrl": {
                    "type": "string"
                }
            }
        },
        "user.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string"
                },
                "profileImageId": {
                    "type": "integer"
                }
            }
        },
        "user.UpdateUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fbProviderType": {
                    "$ref": "#/definitions/user.FirebaseProviderType"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "profileImageUrl": {
                    "type": "string"
                }
            }
        },
        "user.UserRegistrationStatus": {
            "type": "string",
            "enum": [
                "NOT_REGISTERED",
                "REGISTERED"
            ],
            "x-enum-varnames": [
                "UserStatusNotRegistered",
                "UserStatusRegistered"
            ]
        },
        "user.UserStatusRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "user.UserStatusView": {
            "type": "object",
            "properties": {
                "fbProviderType": {
                    "$ref": "#/definitions/user.FirebaseProviderType"
                },
                "status": {
                    "$ref": "#/definitions/user.UserRegistrationStatus"
                }
            }
        }
    },
    "securityDefinitions": {
        "FirebaseAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.6.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "이웃집멍냥 API 문서",
	Description:      "이웃집멍냥 백엔드 API 문서입니다.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
