// Code generated by "stringer -type=GenderCondition"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Male-0]
	_ = x[Female-1]
	_ = x[All-2]
}

const _GenderCondition_name = "MaleFemaleAll"

var _GenderCondition_index = [...]uint8{0, 4, 10, 13}

func (i GenderCondition) String() string {
	if i < 0 || i >= GenderCondition(len(_GenderCondition_index)-1) {
		return "GenderCondition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GenderCondition_name[_GenderCondition_index[i]:_GenderCondition_index[i+1]]
}
