name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up database
        run: docker-compose -f docker-compose-test.yml up -d

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'

      - name: Generate Swagger
        run: go install github.com/swaggo/swag/cmd/swag@latest && source ./scripts/swagger-gen.sh

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -p 1
